### PR TITLE
fix: typescript crashes

### LINKED ISSUE #478: OperationIDs with a slash are breaking code generation
Screen Shot 2022-07-11 at 11 38 08 AM

image

### PR DESCRIPTION
**Pull request by erunion**
| 🚥 Fix #478 |
| :-- |

## 🧰 Changes

This fixes a few quirks that'd cause TS compilation to crash:

* [x] If an operation didn't have `responses` or had `responses: {}` we'd crash when trying to reduce an empty array.
* [x] If an operation had an `operationId` that had characters that can't be used in a JS accessor we'd crash.
  * I actually fixed this in [oas](https://npm.im/oas) back in February (https://github.com/readmeio/oas/pull/602) by adding a `camelCase` option to `getOperationId` but forgot to update TS generation to use it.

## 🧬 QA & Testing

See tests.

### CODE REVIEW

File: packages/api/src/cli/codegen/languages/typescript.ts [hunk 1]
```diff
@@ -673,12 +673,17 @@ sdk.server('https://eu.api.example.com/v14');`)
       Object.entries(ops).forEach(([method, operation]: [HttpMethods, Operation]) => {
         methods.add(method);
 
-        const operationId = operation.getOperationId();
+        const operationId = operation.getOperationId({
+          // This `camelCase` option will clean up any weird characters that might be present in
+          // the `operationId` so as we don't break TS compilation with an invalid method accessor.
+          camelCase: true,
```
Comment (kanadgupta) [inline packages/api/src/cli/codegen/languages/typescript.ts:679]: I love how you already wrote support for this and you just forgot to enable it lmao

**Review by kanadgupta — APPROVED** [review]

File: packages/api/src/cli/codegen/languages/typescript.ts (hunk 1 above)
Comment (erunion) [reply packages/api/src/cli/codegen/languages/typescript.ts:679]: lol me
